apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy4789
  labels:
    app: autodeploy4789
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717493224727
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy4789
  template:
    metadata:
      labels:
        app: autodeploy4789
    spec:
      containers:
        - name: autodeploy4789
          image: acrworkflow1717493224727.azurecr.io/image-workflow-1717493224727:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
