apiVersion: v1
kind: Service
metadata:
  name: autodeploy4789
  namespace: namespace-workflow-1717493224727
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy4789
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000